# Generated by Django 5.0.2 on 2024-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
